# -*- coding: utf-8 -*-
"""Formation_control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rweJlpYip7cRcvBfLLSsDZLScxNLZlR7
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter

N = 20
p = 0.25
seed = 42

np.random.seed(seed)

dt = 0.05
steps_per_letter = 100
settling_steps = 20

k = 1.5

letter_width = 6.0
letter_height = 6.0

while True:
    G = nx.erdos_renyi_graph(
        N,
        p,
        seed=np.random.randint(0, 100000)
    )
    if nx.is_connected(G):
        break

A = nx.to_numpy_array(G)

D = np.diag(np.sum(A, axis=1))

L = D - A

print("Number of agents:", N)
print("Edge probability:", p)
print("Number of edges:", G.number_of_edges())
print("Graph connected:", nx.is_connected(G))

x = np.random.uniform(
    low=-8,
    high=8,
    size=(N, 2)
)

initial_positions = x.copy()

def line_points(p1, p2, n):
    t = np.linspace(0, 1, n)
    return np.array([
        p1 + ti * (p2 - p1)
        for ti in t
    ])

def create_T():
    points = []

    points.extend(
        line_points(
            np.array([-3.0, 3.0]),
            np.array([3.0, 3.0]),
            10
        )
    )

    points.extend(
        line_points(
            np.array([0.0, 3.0]),
            np.array([0.0, -3.0]),
            10
        )
    )

    return np.array(points)

def create_A():
    left = line_points(
        np.array([-3.0, -3.0]),
        np.array([0.0, 3.0]),
        8
    )

    right = line_points(
        np.array([0.0, 3.0]),
        np.array([3.0, -3.0]),
        8
    )

    middle = line_points(
        np.array([-1.5, 0.0]),
        np.array([1.5, 0.0]),
        4
    )

    return np.vstack((left, right, middle))

def create_N():
    left = line_points(
        np.array([-3.0, -3.0]),
        np.array([-3.0, 3.0]),
        7
    )

    diagonal = line_points(
        np.array([-3.0, 3.0]),
        np.array([3.0, -3.0]),
        6
    )

    right = line_points(
        np.array([3.0, -3.0]),
        np.array([3.0, 3.0]),
        7
    )

    return np.vstack((left, diagonal, right))

def create_U():
    left = line_points(
        np.array([-3.0, 3.0]),
        np.array([-3.0, -2.0]),
        7
    )

    bottom = line_points(
        np.array([-3.0, -2.0]),
        np.array([3.0, -2.0]),
        6
    )

    right = line_points(
        np.array([3.0, -2.0]),
        np.array([3.0, 3.0]),
        7
    )

    return np.vstack((left, bottom, right))

def create_S():
    top = line_points(
        np.array([3.0, 3.0]),
        np.array([-3.0, 3.0]),
        5
    )

    upper_diag = line_points(
        np.array([-3.0, 3.0]),
        np.array([-3.0, 0.0]),
        4
    )

    middle = line_points(
        np.array([-3.0, 0.0]),
        np.array([3.0, 0.0]),
        5
    )

    lower_diag = line_points(
        np.array([3.0, 0.0]),
        np.array([3.0, -3.0]),
        3
    )

    bottom = line_points(
        np.array([3.0, -3.0]),
        np.array([-3.0, -3.0]),
        3
    )

    return np.vstack(
        (top, upper_diag, middle, lower_diag, bottom)
    )

def create_H():
    left = line_points(
        np.array([-3.0, -3.0]),
        np.array([-3.0, 3.0]),
        7
    )

    middle = line_points(
        np.array([-3.0, 0.0]),
        np.array([3.0, 0.0]),
        6
    )

    right = line_points(
        np.array([3.0, -3.0]),
        np.array([3.0, 3.0]),
        7
    )

    return np.vstack((left, middle, right))

letters = {
    "T": create_T(),
    "A": create_A(),
    "N": create_N(),
    "U": create_U(),
    "S": create_S(),
    "H": create_H()
}

def adjust_points(points, n):
    m = len(points)

    if m == n:
        return points

    if m > n:
        indices = np.linspace(0, m - 1, n).astype(int)
        return points[indices]

    indices = np.linspace(0, m - 1, n).astype(int)

    return points[indices]

for letter in letters:
    letters[letter] = adjust_points(
        letters[letter],
        N
    )

def formation_control_step(x, target):
    error = x - target

    u = -k * L @ error

    return u

trajectory = []
letter_labels = []

current_x = x.copy()

trajectory.append(current_x.copy())
letter_labels.append("Initial Position")

name = "TANUSH"

for letter in name:
    target = letters[letter]

    for step in range(steps_per_letter):
        u = formation_control_step(
            current_x,
            target
        )

        current_x = current_x + dt * u

        trajectory.append(
            current_x.copy()
        )

        letter_labels.append(letter)

    for step in range(settling_steps):
        trajectory.append(
            current_x.copy()
        )

        letter_labels.append(letter)

trajectory = np.array(trajectory)

plt.figure(figsize=(7, 7))

pos_graph = nx.spring_layout(
    G,
    seed=seed
)

nx.draw_networkx_edges(
    G,
    pos_graph,
    edge_color="gray",
    width=1.2,
    alpha=0.55
)

nx.draw_networkx_nodes(
    G,
    pos_graph,
    node_size=500,
    node_color="lightblue",
    edgecolors="gray"
)

nx.draw_networkx_labels(
    G,
    pos_graph
)

plt.title(
    "Connected Erdos-Renyi Communication Graph"
)

plt.axis("off")

plt.savefig(
    "communication_graph.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close()

fig, ax = plt.subplots(figsize=(8, 8))

ax.set_xlim(-8, 8)
ax.set_ylim(-8, 8)

ax.set_aspect("equal")

ax.set_xlabel("x-coordinate")
ax.set_ylabel("y-coordinate")

ax.grid(True)

scatter = ax.scatter(
    trajectory[0, :, 0],
    trajectory[0, :, 1],
    s=100,
    color="lightblue",
    edgecolors="gray"
)

edge_lines = []

for i, j in G.edges():
    line, = ax.plot(
        [
            trajectory[0, i, 0],
            trajectory[0, j, 0]
        ],
        [
            trajectory[0, i, 1],
            trajectory[0, j, 1]
        ],
        color="gray",
        alpha=0.5,
        linewidth=1.2
    )

    edge_lines.append(line)

title = ax.set_title(
    "TANUSH Formation Control\nInitial Position"
)

def update(frame):
    positions = trajectory[frame]

    scatter.set_offsets(positions)

    for line, (i, j) in zip(
        edge_lines,
        G.edges()
    ):
        line.set_data(
            [
                positions[i, 0],
                positions[j, 0]
            ],
            [
                positions[i, 1],
                positions[j, 1]
            ]
        )

    current_letter = letter_labels[frame]

    if current_letter == "Initial Position":
        title.set_text(
            "TANUSH Formation Control\n"
            "Initial Random Positions"
        )
    else:
        title.set_text(
            "TANUSH Formation Control\n"
            "Current Formation: " + current_letter
        )

    return [scatter, title] + edge_lines

animation = FuncAnimation(
    fig,
    update,
    frames=len(trajectory),
    interval=50,
    blit=False
)

print("\nSaving animation...")

writer = FFMpegWriter(
    fps=20,
    bitrate=1800
)

animation.save(
    "TANUSH_formation_control.mp4",
    writer=writer
)

print("Video saved as:")
print("TANUSH_formation_control.mp4")

plt.show()

for letter in name:
    plt.figure(figsize=(7, 7))

    target = letters[letter]

    plt.scatter(
        target[:, 0],
        target[:, 1],
        s=150,
        color="lightblue",
        edgecolors="gray"
    )

    plt.xlim(-4, 4)
    plt.ylim(-4, 4)

    plt.gca().set_aspect("equal")

    plt.grid(True)

    plt.xlabel("x-coordinate")
    plt.ylabel("y-coordinate")

    plt.title(
        "Target Formation: " + letter
    )

    plt.savefig(
        "formation_" + letter + ".png",
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

print("\nAll formations saved successfully.")
print("Files generated:")
print("communication_graph.png")
print("formation_T.png")
print("formation_A.png")
print("formation_N.png")
print("formation_U.png")
print("formation_S.png")
print("formation_H.png")
print("TANUSH_formation_control.mp4")